

<?= $this->getLayout()->createBlock('cms/block')->setBlockId('sub-main-banner-red')->toHtml(); 
echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribepopup.phtml')->toHtml();

?>
{{block type="core/template" name="homePageBlock" template="page/html/home.phtml"}}


<?php
/**
 * Create custom attribute in magento
 * Lưu ý: tên biến không được có số
 * app/local/customerAttribute/sql/custom_setup/mysql4-install-0.1.0.php
 */

$installer->addAttribute("customer", "fix_state_issued_by",  array(
    "type"     => "varchar",
    "backend"  => "",
    "label"    => "State Issued By",
    "input"    => "text",
    "source"   => "",
    "visible"  => true,
    "required" => false,
    "default" => "",
    "frontend" => "",
    "unique"     => false,
    "note"       => ""

));

$attribute   = Mage::getSingleton("eav/config")->getAttribute("customer", "fix_state_issued_by");
$used_in_forms=array();
$used_in_forms[]="adminhtml_customer";
$used_in_forms[]="checkout_register";
$used_in_forms[]="customer_account_create";
$used_in_forms[]="customer_account_edit";
$used_in_forms[]="adminhtml_checkout";
$attribute->setData("used_in_forms", $used_in_forms)
    ->setData("is_used_for_customer_segment", true)
    ->setData("is_system", 0)
    ->setData("is_user_defined", 1)
    ->setData("is_visible", 1)
    ->setData("sort_order", 100)
;
$attribute->save();




$installer->addAttribute("customer", "fix_resale_expired",  array(
    "type"     => "datetime",
    "backend"  => "eav/entity_attribute_backend_datetime",
    "label"    => "Expiration Date",
    "input"    => "date",
    "source"   => "",
    "visible"  => true,
    "required" => false,
    "default" => "",
    "frontend" => "",
    "unique"     => false,
    "note"       => ""

));

$attribute   = Mage::getSingleton("eav/config")->getAttribute("customer", "fix_resale_expired");
$used_in_forms=array();
$used_in_forms[]="adminhtml_customer";
$used_in_forms[]="checkout_register";
$used_in_forms[]="customer_account_create";
$used_in_forms[]="customer_account_edit";
$used_in_forms[]="adminhtml_checkout";
$attribute->setData("used_in_forms", $used_in_forms)
    ->setData("is_used_for_customer_segment", true)
    ->setData("is_system", 0)
    ->setData("is_user_defined", 1)
    ->setData("is_visible", 1)
    ->setData("sort_order", 100)
;
$attribute->save();

// # Create custom attribute in magento
?>

<?php
// Get Custom Attribute in Magento
$_product= Mage::getSingleton('catalog/product')->load($_item->getProductId());
echo $_product->getResource()->getAttribute('attributeCode')->getFrontend()->getValue($_product);
$product->getData("attributeCode");
$product->getAttributeText("attributeCode");
// # Get Custom Attribute in Magento

// Get Order ID Magento
$_order->getRealOrderId(); //  100000064
$_order->getIncrementId();  // 100000064
$_order->getEntityId(); // 64

//Get Stock status isinstock Magento
$product->getStockItem()->getIsInStock();

//Get Current link url Magento
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$path = Mage::getSingleton('core/url')->parseUrl($currentUrl)->getPath();
$baseUrl = Mage::getBaseUrl();

// Sort by in list page
/** catalog/product/list/toolbar.phtml **/
$toolbar = Mage::getBlockSingleton('catalog/product_list_toolbar');
$s = $toolbar->getCurrentOrder();
$d = $toolbar->getCurrentDirection(); 
$this->getOrderUrl('name', 'asc'); // Link url sort 
$this->getOrderUrl('price', 'desc'); // Link url sort

public function setDefaultOrder($field)
{
    if (isset($this->_availableOrder[$field])) {
        $this->_availableOrder = array(
            'recentlyadded' => $this->__('Recently Added'),
            'name' => $this->__('Name'),
            'price' => $this->__('Price'),
            'created_at' => $this->__('Created Date')
        );
        $this->_orderField = $field;
    }
    return $this;
}

/**
 * Get MSRP Price ( Manufacturer’s Suggested Retail Price ) Magento
 * "true" for price format.
 * "false" for no html.
 * Reference: http://siven76.com/2013/03/08/magento-display-manufacturers-suggested-retail-price/
 */
$_msrpPrice = $this->helper('core')->currency($_product->getMsrp(),true,true);


// open up /app/code/core/Mage/Paygate/Model/Authorizenet.php
// find code
const CGI_URL_TD = 'https://apitest.authorize.net/xml/v1/request.api';
// and replace the url with
const CGI_URL_TD = 'https://api.authorize.net/xml/v1/request.api';
// Then go to your magento admin sales->order , click on any order status with “Suspected 


//  Remove link in dashboard page. /template/customer/account/navigation.phtml
$_count = count($_links); /* Add or Remove Account Left Navigation Links Here -*/

unset($_links['account']);
unset($_links['account_edit']);
unset($_links['address_book']);
unset($_links['orders']);
unset($_links['billing_agreements']); /* Billing Agreements */
unset($_links['recurring_profiles']); /* Recurring Profiles */
unset($_links['reviews']);
unset($_links['tags']); /* My Tags */
unset($_links['wishlist']);
unset($_links['OAuth Customer Tokens']); /* My Applications */
unset($_links['downloadable_products']); /* My Downloadable Products */
unset($_links['aw_storecredit']);

unset($_links['invitations']); /* My Invitations */
unset($_links['enterprise_customerbalance']); /* Store Credit */
unset($_links['enterprise_reward']); /* Reward Points */
unset($_links['giftregistry']); /* Gift Registry */
unset($_links['enterprise_giftcardaccount']); /* Gift Card Link */    

?>

<!--Permission file and folder in Magento-->
sudo find /var/www/html/magentoInstallationFolder/ -type d -exec chmod 775 {} \;
sudo find /var/www/html/magentoInstallationFolder/ -type f -exec chmod 664 {} \;
sudo find -type d -exec chmod 775 {} \;
sudo find -type f -exec chmod 664 {} \;
Set Writable for 3 folders in root magento: var, media, app/etc
sudo chmod -R 777 var/  media/ app/etc/ downloader/


<!--Service Temporarily Unavailable - Magento-->
Bug: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
Check if there is a file called maintenance.flag in your magento root. If so Delete it.
Delete all file in magentoRoot/var/cache/* : sudo rm -rf magento/var/cache/*
Reference: http://stackoverflow.com/questions/8102777/service-temporarily-unavailable-magento

<!--Fix bugs: White page, Blank Page in magento-->
In file index.php. You recomment // ini_set('display_errors', 1);
Result: ini_set('display_errors', 1);
Check erros code of white page. Make sure codes of Core Magento, Modules, ... are true.
Clear cache, Reindex in Admin magento. Remove caches in magento/var/cache/*
FINAL: Permision files of magento. Link
http://letunhatkong.blogspot.com/2015/07/permission-file-and-folder-in-magento.html


<!--Remove /index.php from URL in magento-->
Mặc định thì magento phiên bản > 1.9.1.1 đã fix lỗi này.
Kiểm tra admin magento
'System > Configuration > Web > 'Search Engine Optimisation' tab
select 'YES' underneath the 'Use Web Server Rewrites' option.
Kiểm tra file .htaccess có các dòng sau không
(phiên bản magento > 1.9.1.1 thì ko cần kiểm tra )
Options +FollowSymLinks
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule . index.php [L]


<!--INSTALL MAGENTO IN LINUX-->
Read more:
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-magento-on-ubuntu-14-04

sudo apt-get update
sudo apt-get install apache2

sudo apt-get install mysql-server php5-mysql
sudo mysql_install_db
sudo mysql_secure_installation

sudo apt-get install php5 libapache2-mod-php5 php5-mcrypt libcurl3 php5-curl php5-gd

sudo nano /etc/apache2/mods-enabled/dir.conf
Change line: DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm

sudo nano /etc/apache2/sites-available/wrm1.conf

<VirtualHost wrm1.vn:80>
    ServerAdmin wrm1@localhost
    DocumentRoot /var/www/html/wrm1
    ServerName wrm1.vn

    <Directory /var/www/html/wrm1>
        Allow from all
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/wrm1-log.log
    CustomLog ${APACHE_LOG_DIR}/wrm1-access.log combined

</VirtualHost>



sudo a2ensite wrm1.conf
sudo a2dissite 000-default.conf

sudo a2enmod rewrite
sudo php5enmod mcrypt

mysql -u root -p
CREATE DATABASE wrm1; CREATE USER wrm1@localhost IDENTIFIED BY '1'; GRANT ALL PRIVILEGES ON wrm1.* TO wrm1@localhost IDENTIFIED BY '1'; FLUSH PRIVILEGES;
exit

Copy magento folder to this path /var/www/html/

Permission folder
sudo find /var/www/html/magentoInstallationFolder/ -type d -exec chmod 775 {} \;
sudo find /var/www/html/magentoInstallationFolder/ -type f -exec chmod 664 {} \;

sudo find -type d -exec chmod 775 {} \; &&  sudo find -type f -exec chmod 664 {} \; && sudo chmod -R 777 var/  media/ app/etc/ downloader/;

Set Writable for 3 folders in root magento: var, media, app/etc
sudo chmod -R 777 var/  media/ app/etc/ downloader/












