<!-- Re-INDEX -->
sudo php bin/magento indexer:reindex

<!-- Re-DEPLOY -->
sudo php bin/magento setup:static-content:deploy
// M2 có 2 chế độ symlink and copy. deploy content => copy.
// Nếu M2 ko tự động tạo symlink khi F5 page thì có nghĩa là cần xem lại file .htaccess của thư mục pub/static
https://github.com/magento/magento2/blob/develop/pub/static/.htaccess

sudo rm -rf var/cache/ var/page_cache/ var/view_preprocessed/ var/composer_home/ pub/static/* var/generation/; sudo php bin/magento setup:static-content:deploy; sudo php bin/magento indexer:reindex; sudo chmod -R 777 var/ pub/ app/design;

cd /home/ubuntu/tradebanner/; git pull; sudo rsync -avP . /var/www/html/; cd /var/www/html/; sudo rm -rf var/cache/ var/page_cache/ var/view_preprocessed/ var/composer_home/ pub/static/* var/generation/ var/di; sudo php bin/magento setup:static-content:deploy; sudo php bin/magento indexer:reindex; sudo chmod -R 777 var/ pub/;

sudo rm -rf var/cache/ var/page_cache/ var/view_preprocessed/ var/composer_home/ var/generation/ var/di/; 


sudo rm -rf var/cache/ var/page_cache/ var/view_preprocessed/ pub/static/* ; 
sudo php bin/magento setup:static-content:deploy; 
sudo chmod -R 777 var/ pub/;

<!-- Upgrade -->
sudo php bin/magento setup:upgrade; sudo chmod -R 777 var/ pub/;
sudo rm -rf var/di/; sudo php bin/magento setup:di:compile;

<!-- Add new theme -->
sudo php bin/magento deploy:mode:show
sudo php bin/magento deploy:mode:set developer
Server phai bat developer mode

<!-- CLEAR CACHE -->
Go to magento folder and type: 
sudo php bin/magento cache:clean
sudo php bin/magento cache:fluid
Edit code trong html 
sudo rm -rf var/cache/ var/page_cache/ var/view_preprocessed/ var/composer_home/  pub/static/* var/generation/ var/di

<!-- Show mode -->
sudo php bin/magento deploy:mode:show
sudo php bin/magento deploy:mode:set developer
sudo php bin/magento deploy:mode:set production

<!-- List Module Status -->
sudo php bin/magento module:status

<!-- Install MAGENTO 2 -->
1/ Install apache2: sudo apt-get install apache2 

2/ PHP extension
==== INSTALL PHP 5.6.x
sudo apt-get -y update
sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get -y update
sudo apt-get -y install php5 php5-common php5-mcrypt php5-curl php5-cli php5-mysql php5-gd php5-intl php5-xsl libapache2-mod-php5 libcurl3 php5-imagick zip
sudo apt-get install mysql-server-5.6 php5-mysql

==== INSTALL PHP 7
sudo apt-get -y update; sudo add-apt-repository ppa:ondrej/php; sudo apt-get -y update; sudo apt-get install -y php7.0 libapache2-mod-php7.0 php7.0 php7.0-common php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-curl php7.0-intl php7.0-xsl php7.0-mbstring php7.0-zip php7.0-bcmath php7.0-iconv;
sudo apt install -y mysql-server mysql-client;
sudo mysql_secure_installation


3/ Config memory_limit of PHP
Ubuntu: sudo nano /etc/php5/cli/php.ini and sudo nano /etc/php5/apache2/php.ini
/etc/php/7.0/cli/php.ini and /etc/php/7.0/apache2/php.ini

memory_limit = 768M or 1G
post_max_size 100M
always_populate_raw_post_data = -1 (removed on php7)
upload_max_filesize 100M
opcache.save_comments 1 (only php 7)

mod_rewrite module must be enabled: sudo a2enmod rewrite
sudo service apache2 restart

4/ Create vitrual machine
sudo nano /etc/apache2/sites-available/magento.conf                    

<Directory /var/www/html>
    Allow from all
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
</Directory>

<VirtualHost siva.vn:80>
    ServerAdmin siva@localhost
    DocumentRoot /var/www/html/siva
    ServerName siva.vn

    <Directory /var/www/html/siva>
        Allow from all
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/siva-log.log
    CustomLog ${APACHE_LOG_DIR}/siva-access.log combined

</VirtualHost>
# sudo nano /etc/hosts
127.0.1.1 siva.vn

sudo a2ensite magento.conf 
sudo service apache2 reload
sudo service apache2 restart

5/ Create DATABASE
mysql -u root -p
CREATE DATABASE tradebanner DEFAULT CHARACTER SET utf8; CREATE USER tradebanner@localhost IDENTIFIED BY 'simple123'; GRANT ALL PRIVILEGES ON tradebanner.* TO tradebanner@localhost IDENTIFIED BY 'simple123'; FLUSH PRIVILEGES; 

6/ Permission folders and files
cd to /var/www/html and type: sudo chown -R :www-data magento-folder

sudo find . -type d -exec chmod 775 {} \; && sudo find . -type f -exec chmod 664 {} \; && sudo chmod -R 777 bin/magento var/ pub/ app/etc/ app/design/frontend/; 

sudo find . -type d -exec chmod 777 {} \; && sudo find . -type f -exec chmod 664 {} \; && sudo chmod -R 777 bin/magento var/ pub/ app/etc/ app/design/frontend/ .idea/ .git/ .gitignore;

7/ Go to http://localhost/project-name/setup/

<!-- Remove Module -->
Remove all related tabel, and remove module in setup_module table
DROP TABLE IF EXISTS magefan_blog_category, magefan_blog_category_store;
DELETE FROM setup_module WHERE module = "Magefan_Blog";
sudo php bin/magento module:uninstall Magentostudy_News --backup-code --backup-media --backup-db --clear-static-content
<!-- Disable Module -->
sudo php bin/magento module:disable Lexim_Catalog
<!-- Enable Module -->
php bin/magento module:enable Sahy_Banner --clear-static-content

<!-- Update Magento 2 -->
The second way is with composer:
In composer.json change this line
"magento/product-community-edition": "2.0.0",
Also you should change the line 5 as well "version": "2.0.0", to keep it in sync.
to whatever version you want, and then run:
composer update
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy

To upgrade to 2.0.7 using the command line: cd /var/www/html/magento2
php bin/magento cache:disable
composer require magento/product-community-edition 2.0.7 --no-update
composer update
php bin/magento setup:upgrade
php bin/magento cache:enable

<!-- ===== UPDATE URL BASE ==== -->
UPDATE core_config_data SET value = 'http://tradebanner.com/' WHERE config_id = 2; UPDATE core_config_data SET value = 'https://tradebanner.com/' WHERE config_id = 3; 